[package]
name = "ork-web"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net"] }
tower-http = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
ork-core = { path = "../ork-core" }
ork-state = { path = "../ork-state" }
ork-runner = { path = "../ork-runner" }
