[project]
name = "metaflow-examples"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "metaflow>=2.19.15",
]

[dependency-groups]
dev = [
    "pyright>=1.1.408",
    "ruff>=0.14.11",
]
